BALL_RAD = 20
BALL_SPEED = 8
MAX_BALL_SPEED = 28
BALL_DELTA_VEL = 0.015
RND_ANG_DISPERS = 10
ANG_HIST_MAX=75
ANG_RND_DISP_MAX=3
WITH_SLIDER='slider'
WITH_LINE_LEFT='line_left'
WITH_LINE_RIGHT='line_right'
WITH_GOAL_LEFT='goal_left'
WITH_GOAL_RIGHT='goal_right'
WITH_POST = 'post'

MIN_SPARKLES_AMOUNT = 60
MAX_SPARKLES_AMOUNT = 80
