#!/usr/bin/python

DISPLAY_W = 1000
DISPLAY_H = 600
DISPLAY_SIZE = (DISPLAY_W, DISPLAY_H)
FIELD_W = 800
FIELD_H = 600
BORDER_HEIGHT = 20
NET_SIZE = 30
GOAL_AREA = NET_SIZE
L_GOAL_LINE = GOAL_AREA
R_GOAL_LINE = FIELD_W - GOAL_AREA
GOAL_LINE_SIZE_PERCENT = 0.6
NET_DENSE = 25
POST_SIZE = 30
POST_OFFSET_Y = int((FIELD_H - FIELD_H*GOAL_LINE_SIZE_PERCENT)/2) + POST_SIZE/2
POST_BOT_Y = FIELD_H - POST_OFFSET_Y
POST_LEFT_X = L_GOAL_LINE
POST_TOP_Y = POST_OFFSET_Y
POST_RIGHT_X = R_GOAL_LINE
BKG_IMG = 'pic/bkg11.jpg'
POST_IMG = 'pic/post.png'
BORDER_TOP_IMG = 'pic/border_top.png'
BORDER_BOT_IMG = 'pic/border_bot.png'
BORDER_SIDE_IMG = 'pic/border_side.png'
CENTER_LINE_IMG = 'pic/center_line.png'
GOAL_LINE_IMG = 'pic/goal_line.png'

