#!/usr/bin/python

DISPLAY_W = 1000
DISPLAY_H = 600
DISPLAY_SIZE = (DISPLAY_W, DISPLAY_H)
FIELD_W = 800
FIELD_H = 600
FIELD_CENTER_SIZE = 25
NET_SIZE = 30
GOAL_AREA = NET_SIZE
L_GOAL_LINE = GOAL_AREA
R_GOAL_LINE = FIELD_W - GOAL_AREA
NET_DENSE = 25
POST_SIZE = 25 
